//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zavrsni2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KosaraProizvod
    {
        public int ID { get; set; }
        public Nullable<int> Kosara_ID { get; set; }
        public Nullable<int> Proizvod_ID { get; set; }
        public Nullable<int> Kolicina { get; set; }
    
        public virtual Kosara Kosara { get; set; }
        public virtual Proizvod Proizvod { get; set; }
    }
}
