//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zavrsni2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod()
        {
            this.KosaraProizvod = new HashSet<KosaraProizvod>();
        }
    
        public int ID { get; set; }
        public string Slika { get; set; }
        public string Ime { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DatumDodavanje { get; set; }
        public Nullable<double> Cijena { get; set; }
        public string KratakOpis { get; set; }
        public Nullable<int> Kategorija_ID { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<int> ProdanaKolicina { get; set; }
    
        public virtual Kategorija Kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KosaraProizvod> KosaraProizvod { get; set; }
    }
}
