//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zavrsni2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string Broj_mobitela { get; set; }
        public string Uloga { get; set; }
        public Nullable<int> ID_Uloga { get; set; }
    
        public virtual Uloga Uloga1 { get; set; }
    }
}
